### PR TITLE
Fix reflection extensions

### PR DESCRIPTION
**Pull request by ghost**
Oops made a mistake (it broke net4 and net45 build). Now its all good. :)

### CODE REVIEW

**Comment by alexandrnikitin** [comment]
:+1: Thanks

**Comment by ghost** [comment]
I haven't fixed the failing test issues. Do you have idea how to fix those?

**Comment by alexandrnikitin** [comment]
Those tests suppose to fail :blush: They are marked as `Explicit`. CLI takes that into account and ignores them. But the VS Test Explorer doesn't. I didn't check the sources of `dotnet-test-nunit` yet.

**Comment by ghost** [comment]
True all Explicit failures are warnings. But on macOS I have actually three tests failing:

``` sh
1) Failed : NSubstitute.Acceptance.Specs.FormattingCallsWhenThrowingReceivedCallsExceptions+When_not_enough_matching_calls_were_made_to_a_method.Should_list_actual_related_calls
  Expected: String containing "Received 1 non-matching call (non-matching arguments indicated with '*' characters):
    SampleMethod(*1*)"
  But was:  "Expected to receive exactly 2 calls matching:
    SampleMethod(2)
Actually received 1 matching call:
    SampleMethod(2)
Received 1 non-matching call (non-matching arguments indicated with '*' characters):
    SampleMethod(*1*)
"
at NSubstitute.Acceptance.Specs.FormattingCallsWhenThrowingReceivedCallsExceptions.Context.ExceptionMessageContains(String expected) in /Users/peter/test1/NSubstitute/Source/NSubstitute.Acceptance.Specs/FormattingCallsWhenThrowingReceivedCallsExceptions.cs:line 415
at NSubstitute.Acceptance.Specs.FormattingCallsWhenThrowingReceivedCallsExceptions.When_not_enough_matching_calls_were_made_to_a_method.Should_list_actual_related_calls() in /Users/peter/test1/NSubstitute/Source/NSubstitute.Acceptance.Specs/FormattingCallsWhenThrowingReceivedCallsExceptions.cs:line 127
2) Failed : NSubstitute.Acceptance.Specs.FormattingCallsWhenThrowingReceivedCallsExceptions+When_not_enough_matching_calls_were_made_to_a_method.Should_list_matching_calls
  Expected: String containing "Actually received 1 matching call:
    SampleMethod(2)"
  But was:  "Expected to receive exactly 2 calls matching:
    SampleMethod(2)
Actually received 1 matching call:
    SampleMethod(2)
Received 1 non-matching call (non-matching arguments indicated with '*' characters):
    SampleMethod(*1*)
"
at NSubstitute.Acceptance.Specs.FormattingCallsWhenThrowingReceivedCallsExceptions.Context.ExceptionMessageContains(String expected) in /Users/peter/test1/NSubstitute/Source/NSubstitute.Acceptance.Specs/FormattingCallsWhenThrowingReceivedCallsExceptions.cs:line 415
at NSubstitute.Acceptance.Specs.FormattingCallsWhenThrowingReceivedCallsExceptions.When_not_enough_matching_calls_were_made_to_a_method.Should_list_matching_calls() in /Users/peter/test1/NSubstitute/Source/NSubstitute.Acceptance.Specs/FormattingCallsWhenThrowingReceivedCallsExceptions.cs:line 121
3) Failed : NSubstitute.Acceptance.Specs.FormattingCallsWhenThrowingReceivedCallsExceptions+When_too_many_matching_calls_were_made_to_a_method.Should_list_matching_calls
  Expected: String containing "Actually received 3 matching calls:
    SampleMethod(2)"
  But was:  "Expected to receive exactly 2 calls matching:
    SampleMethod(2)
Actually received 3 matching calls:
    SampleMethod(2)
    SampleMethod(2)
    SampleMethod(2)
"
at NSubstitute.Acceptance.Specs.FormattingCallsWhenThrowingReceivedCallsExceptions.Context.ExceptionMessageContains(String expected) in /Users/peter/test1/NSubstitute/Source/NSubstitute.Acceptance.Specs/FormattingCallsWhenThrowingReceivedCallsExceptions.cs:line 415
at NSubstitute.Acceptance.Specs.FormattingCallsWhenThrowingReceivedCallsExceptions.When_too_many_matching_calls_were_made_to_a_method.Should_list_matching_calls() in /Users/peter/test1/NSubstitute/Source/NSubstitute.Acceptance.Specs/FormattingCallsWhenThrowingReceivedCallsExceptions.cs:line 155
Run Settings
    WorkDirectory: /Users/peter/test1/NSubstitute
Test Run Summary
  Overall result: Failed
  Test Count: 404, Passed: 383, Failed: 3, Inconclusive: 0, Skipped: 18
    Failed Tests - Failures: 3, Errors: 0, Invalid: 0
    Skipped Tests - Ignored: 6, Explicit: 12, Other: 0
```

**Comment by alexandrnikitin** [comment]
I have the same tests failing on Ubuntu. Looking into it.

**Comment by ghost** [comment]
Hopefully this is not some CoreCLR bug. :sweat_smile:

**Comment by alexandrnikitin** [comment]
No, it's related to the new line special characters in windows/unix/mac.

**Comment by ghost** [comment]
Ops, I thought it is concatenating two exception messages.

**Pull request merged**
