### PR TITLE
Issue192 net core project 2

### PR DESCRIPTION
**Pull request by dtchepak**
Added "netstandard1.5" to targets.

Some example builds (from Git Bash on Windows):

```
# full build, dotnet core only
> ./build.sh All targets=netstandard1.5
# full build, net35 only
> ./build.sh All targets=NET35
# full build, all platforms
> ./build.sh All targets=ALL
# full build, all platforms, label package as beta4
>  ./build.sh All targets=ALL packageVersionSuffix=beta4
# show config options
> ./build.sh -T
# just clean/version/build, all platforms, release mode
> ./build.sh Build targets=ALL mode=Release
```

I don't know how to do FAKE target dependencies properly, so instead just made a big mess. I tested a few build configurations but haven't tested the generated package itself yet.

### CODE REVIEW

**Comment by alexandrnikitin** [comment]
@dtchepak I'm happy to merge it. Could you re-create this PR against `Issue192_NetCore_Project` branch please.

**Comment by alexandrnikitin** [comment]
Merged in #10

**Comment by dtchepak** [comment]
@alexandrnikitin: did you need me to re-create the PR still? Sorry for pointing it at the wrong branch, I tried to pick `Issue192_NetCore_Project` but seems I failed the Github UI.

**Comment by alexandrnikitin** [comment]
@dtchepak no, I merged it in #10 Everything is fine.

**Pull request closed without merging**
